include ../../Makefile.inc

P=io/part3/
all:
	${GCC} mmap1.c -o mmap1 ${ECHO}mmap1.c
	${GCC} mmap2.c -o mmap2 ${ECHO}mmap2.c
	${GCC} mmap3.c -o mmap3 ${ECHO}mmap3.c
	${GCC} mmap4.c -o mmap4 ${ECHO}mmap4.c
	${GCC} mmap5.c -o mmap5 ${ECHO}mmap5.c
	${GCC} mmap.c -o mmap ${ECHO}mmap.c
	${GCC} mmap_fullfile.c -o mmap_fullfile ${ECHO}mmap_fullfile.c
	${GCC} write.c -o write ${ECHO}write.c

clean:
	${RM} mmap1 mmap2 mmap3 mmap4 mmap5 mmap mmap_fullfile write
