    /*
 The MIT License: Copyright (c) 2010-2012 LiosK.
*/
(function(){if(!Function.prototype.bind)Function.prototype.bind=function(b){var c=this;try{if(typeof c!="function")throw new TypeError;}catch(d){}var a=Array.prototype.slice.call(arguments,1),g=function(){if(this instanceof g){var d=function(){};d.prototype=c.prototype;var d=new d,f=c.apply(d,a.concat(Array.prototype.slice.call(arguments)));return Object(f)===f?f:d}else return c.apply(b,a.concat(Array.prototype.slice.call(arguments)))};return g};var a=Function.prototype.call.bind(Object.prototype.toString);
if(!Array.isArray)Array.isArray=function(b){return a(b)=="[object Array]"};if(!Array.prototype.indexOf)Array.prototype.indexOf=function(b){var c;if(this===null||this===void 0)throw new TypeError;c=d&&typeof this=="string"&&this?this.split(""):Object(this);var a=c.length>>>0;if(!a)return-1;var e=0;arguments.length>1&&(e=arguments[1],e=+e,e!==e?e=0:e!==0&&e!==1/0&&e!==-(1/0)&&(e=(e>0||-1)*Math.floor(Math.abs(e))));for(e=e>=0?e:Math.max(0,a+e);e<a;e++)if(e in c&&c[e]===b)return e;return-1};var d="a"[0]!=
"a";String.prototype.inArray=function(b){for(var c=b.length-1;c>=0;c--)if(b[c]==this.toString())return true;return false};if(!Array.prototype.indexOf)Array.prototype.indexOf=function(b,c){var d=this.length>>>0,a=Number(c)||0,a=a<0?Math.ceil(a):Math.floor(a);for(a<0&&(a+=d);a<d;a++)if(a in this&&this[a]===b)return a;return-1}})();var hexcase=0,b64pad="";function hex_sha1(a){return rstr2hex(rstr_sha1(str2rstr_utf8(a)))}
function hex_hmac_sha1(a,d){return rstr2hex(rstr_hmac_sha1(str2rstr_utf8(a),str2rstr_utf8(d)))}function sha1_vm_test(){return hex_sha1("abc").toLowerCase()=="a9993e364706816aba3e25717850c26c9cd0d89d"}function rstr_sha1(a){return binb2rstr(binb_sha1(rstr2binb(a),a.length*8))}
function rstr_hmac_sha1(a,d){var b=rstr2binb(a);b.length>16&&(b=binb_sha1(b,a.length*8));for(var c=Array(16),f=Array(16),e=0;e<16;e++)c[e]=b[e]^909522486,f[e]=b[e]^1549556828;b=binb_sha1(c.concat(rstr2binb(d)),512+d.length*8);return binb2rstr(binb_sha1(f.concat(b),672))}function rstr2hex(a){for(var d=hexcase?"0123456789ABCDEF":"0123456789abcdef",b="",c,f=0;f<a.length;f++)c=a.charCodeAt(f),b+=d.charAt(c>>>4&15)+d.charAt(c&15);return b}
function str2rstr_utf8(a){for(var d="",b=-1,c,f;++b<a.length;)c=a.charCodeAt(b),f=b+1<a.length?a.charCodeAt(b+1):0,55296<=c&&c<=56319&&56320<=f&&f<=57343&&(c=65536+((c&1023)<<10)+(f&1023),b++),c<=127?d+=String.fromCharCode(c):c<=2047?d+=String.fromCharCode(192|c>>>6&31,128|c&63):c<=65535?d+=String.fromCharCode(224|c>>>12&15,128|c>>>6&63,128|c&63):c<=2097151&&(d+=String.fromCharCode(240|c>>>18&7,128|c>>>12&63,128|c>>>6&63,128|c&63));return d}
function rstr2binb(a){for(var d=Array(a.length>>2),b=0;b<d.length;b++)d[b]=0;for(b=0;b<a.length*8;b+=8)d[b>>5]|=(a.charCodeAt(b/8)&255)<<24-b%32;return d}function binb2rstr(a){for(var d="",b=0;b<a.length*32;b+=8)d+=String.fromCharCode(a[b>>5]>>>24-b%32&255);return d}
function binb_sha1(a,d){a[d>>5]|=128<<24-d%32;a[(d+64>>9<<4)+15]=d;for(var b=Array(80),c=1732584193,f=-271733879,e=-1732584194,g=271733878,k=-1009589776,h=0;h<a.length;h+=16){for(var j=c,m=f,n=e,o=g,q=k,l=0;l<80;l++){b[l]=l<16?a[h+l]:bit_rol(b[l-3]^b[l-8]^b[l-14]^b[l-16],1);var r=safe_add(safe_add(bit_rol(c,5),sha1_ft(l,f,e,g)),safe_add(safe_add(k,b[l]),sha1_kt(l))),k=g,g=e,e=bit_rol(f,30),f=c,c=r}c=safe_add(c,j);f=safe_add(f,m);e=safe_add(e,n);g=safe_add(g,o);k=safe_add(k,q)}return[c,f,e,g,k]}
function sha1_ft(a,d,b,c){return a<20?d&b|~d&c:a<40?d^b^c:a<60?d&b|d&c|b&c:d^b^c}function sha1_kt(a){return a<20?1518500249:a<40?1859775393:a<60?-1894007588:-899497514}function safe_add(a,d){var b=(a&65535)+(d&65535);return(a>>16)+(d>>16)+(b>>16)<<16|b&65535}function bit_rol(a,d){return a<<d|a>>>32-d}hexcase=0;function hex_md5(a){return rstr2hex(rstr_md5(str2rstr_utf8(a)))}function hex_hmac_md5(a,d){return rstr2hex(rstr_hmac_md5(str2rstr_utf8(a),str2rstr_utf8(d)))}
function md5_vm_test(){return hex_md5("abc").toLowerCase()=="900150983cd24fb0d6963f7d28e17f72"}function rstr_md5(a){return binl2rstr(binl_md5(rstr2binl(a),a.length*8))}function rstr_hmac_md5(a,d){var b=rstr2binl(a);b.length>16&&(b=binl_md5(b,a.length*8));for(var c=Array(16),f=Array(16),e=0;e<16;e++)c[e]=b[e]^909522486,f[e]=b[e]^1549556828;b=binl_md5(c.concat(rstr2binl(d)),512+d.length*8);return binl2rstr(binl_md5(f.concat(b),640))}
function rstr2hex(a){for(var d=hexcase?"0123456789ABCDEF":"0123456789abcdef",b="",c,f=0;f<a.length;f++)c=a.charCodeAt(f),b+=d.charAt(c>>>4&15)+d.charAt(c&15);return b}
function str2rstr_utf8(a){for(var d="",b=-1,c,f;++b<a.length;)c=a.charCodeAt(b),f=b+1<a.length?a.charCodeAt(b+1):0,55296<=c&&c<=56319&&56320<=f&&f<=57343&&(c=65536+((c&1023)<<10)+(f&1023),b++),c<=127?d+=String.fromCharCode(c):c<=2047?d+=String.fromCharCode(192|c>>>6&31,128|c&63):c<=65535?d+=String.fromCharCode(224|c>>>12&15,128|c>>>6&63,128|c&63):c<=2097151&&(d+=String.fromCharCode(240|c>>>18&7,128|c>>>12&63,128|c>>>6&63,128|c&63));return d}
function rstr2binl(a){for(var d=Array(a.length>>2),b=0;b<d.length;b++)d[b]=0;for(b=0;b<a.length*8;b+=8)d[b>>5]|=(a.charCodeAt(b/8)&255)<<b%32;return d}function binl2rstr(a){for(var d="",b=0;b<a.length*32;b+=8)d+=String.fromCharCode(a[b>>5]>>>b%32&255);return d}
function binl_md5(a,d){a[d>>5]|=128<<d%32;a[(d+64>>>9<<4)+14]=d;for(var b=1732584193,c=-271733879,f=-1732584194,e=271733878,g=0;g<a.length;g+=16)var k=b,h=c,j=f,m=e,b=md5_ff(b,c,f,e,a[g+0],7,-680876936),e=md5_ff(e,b,c,f,a[g+1],12,-389564586),f=md5_ff(f,e,b,c,a[g+2],17,606105819),c=md5_ff(c,f,e,b,a[g+3],22,-1044525330),b=md5_ff(b,c,f,e,a[g+4],7,-176418897),e=md5_ff(e,b,c,f,a[g+5],12,1200080426),f=md5_ff(f,e,b,c,a[g+6],17,-1473231341),c=md5_ff(c,f,e,b,a[g+7],22,-45705983),b=md5_ff(b,c,f,e,a[g+8],7,
1770035416),e=md5_ff(e,b,c,f,a[g+9],12,-1958414417),f=md5_ff(f,e,b,c,a[g+10],17,-42063),c=md5_ff(c,f,e,b,a[g+11],22,-1990404162),b=md5_ff(b,c,f,e,a[g+12],7,1804603682),e=md5_ff(e,b,c,f,a[g+13],12,-40341101),f=md5_ff(f,e,b,c,a[g+14],17,-1502002290),c=md5_ff(c,f,e,b,a[g+15],22,1236535329),b=md5_gg(b,c,f,e,a[g+1],5,-165796510),e=md5_gg(e,b,c,f,a[g+6],9,-1069501632),f=md5_gg(f,e,b,c,a[g+11],14,643717713),c=md5_gg(c,f,e,b,a[g+0],20,-373897302),b=md5_gg(b,c,f,e,a[g+5],5,-701558691),e=md5_gg(e,b,c,f,a[g+
10],9,38016083),f=md5_gg(f,e,b,c,a[g+15],14,-660478335),c=md5_gg(c,f,e,b,a[g+4],20,-405537848),b=md5_gg(b,c,f,e,a[g+9],5,568446438),e=md5_gg(e,b,c,f,a[g+14],9,-1019803690),f=md5_gg(f,e,b,c,a[g+3],14,-187363961),c=md5_gg(c,f,e,b,a[g+8],20,1163531501),b=md5_gg(b,c,f,e,a[g+13],5,-1444681467),e=md5_gg(e,b,c,f,a[g+2],9,-51403784),f=md5_gg(f,e,b,c,a[g+7],14,1735328473),c=md5_gg(c,f,e,b,a[g+12],20,-1926607734),b=md5_hh(b,c,f,e,a[g+5],4,-378558),e=md5_hh(e,b,c,f,a[g+8],11,-2022574463),f=md5_hh(f,e,b,c,a[g+
11],16,1839030562),c=md5_hh(c,f,e,b,a[g+14],23,-35309556),b=md5_hh(b,c,f,e,a[g+1],4,-1530992060),e=md5_hh(e,b,c,f,a[g+4],11,1272893353),f=md5_hh(f,e,b,c,a[g+7],16,-155497632),c=md5_hh(c,f,e,b,a[g+10],23,-1094730640),b=md5_hh(b,c,f,e,a[g+13],4,681279174),e=md5_hh(e,b,c,f,a[g+0],11,-358537222),f=md5_hh(f,e,b,c,a[g+3],16,-722521979),c=md5_hh(c,f,e,b,a[g+6],23,76029189),b=md5_hh(b,c,f,e,a[g+9],4,-640364487),e=md5_hh(e,b,c,f,a[g+12],11,-421815835),f=md5_hh(f,e,b,c,a[g+15],16,530742520),c=md5_hh(c,f,e,
b,a[g+2],23,-995338651),b=md5_ii(b,c,f,e,a[g+0],6,-198630844),e=md5_ii(e,b,c,f,a[g+7],10,1126891415),f=md5_ii(f,e,b,c,a[g+14],15,-1416354905),c=md5_ii(c,f,e,b,a[g+5],21,-57434055),b=md5_ii(b,c,f,e,a[g+12],6,1700485571),e=md5_ii(e,b,c,f,a[g+3],10,-1894986606),f=md5_ii(f,e,b,c,a[g+10],15,-1051523),c=md5_ii(c,f,e,b,a[g+1],21,-2054922799),b=md5_ii(b,c,f,e,a[g+8],6,1873313359),e=md5_ii(e,b,c,f,a[g+15],10,-30611744),f=md5_ii(f,e,b,c,a[g+6],15,-1560198380),c=md5_ii(c,f,e,b,a[g+13],21,1309151649),b=md5_ii(b,
c,f,e,a[g+4],6,-145523070),e=md5_ii(e,b,c,f,a[g+11],10,-1120210379),f=md5_ii(f,e,b,c,a[g+2],15,718787259),c=md5_ii(c,f,e,b,a[g+9],21,-343485551),b=safe_add(b,k),c=safe_add(c,h),f=safe_add(f,j),e=safe_add(e,m);return[b,c,f,e]}function md5_cmn(a,d,b,c,f,e){return safe_add(bit_rol(safe_add(safe_add(d,a),safe_add(c,e)),f),b)}function md5_ff(a,d,b,c,f,e,g){return md5_cmn(d&b|~d&c,a,d,f,e,g)}function md5_gg(a,d,b,c,f,e,g){return md5_cmn(d&c|b&~c,a,d,f,e,g)}
function md5_hh(a,d,b,c,f,e,g){return md5_cmn(d^b^c,a,d,f,e,g)}function md5_ii(a,d,b,c,f,e,g){return md5_cmn(b^(d|~c),a,d,f,e,g)}function safe_add(a,d){var b=(a&65535)+(d&65535);return(a>>16)+(d>>16)+(b>>16)<<16|b&65535}function bit_rol(a,d){return a<<d|a>>>32-d}var UUID;
UUID=function(a){function d(){}d.generate=function(){var b=d._getRandomInt,c=d._hexAligner;return c(b(32),8)+"-"+c(b(16),4)+"-"+c(16384|b(12),4)+"-"+c(32768|b(14),4)+"-"+c(b(48),12)};d._getRandomInt=function(b){return b<0?NaN:b<=30?0|Math.random()*(1<<b):b<=53?(0|Math.random()*1073741824)+(0|Math.random()*(1<<b-30))*1073741824:NaN};d._getIntAligner=function(b){return function(c,a){for(var d=c.toString(b),g=a-d.length,k="0";g>0;g>>>=1,k+=k)g&1&&(d=k+d);return d}};d._hexAligner=d._getIntAligner(16);
d.FIELD_NAMES="timeLow,timeMid,timeHiAndVersion,clockSeqHiAndReserved,clockSeqLow,node".split(",");d.FIELD_SIZES=[32,16,16,8,8,48];d.genV4=function(){var b=d._getRandomInt;return(new d)._init(b(32),b(16),16384|b(12),128|b(6),b(8),b(48))};d.parse=function(b){if(b=/^\s*(urn:uuid:|\{)?([0-9a-f]{8})-([0-9a-f]{4})-([0-9a-f]{4})-([0-9a-f]{2})([0-9a-f]{2})-([0-9a-f]{12})(\})?\s*$/i.exec(b)){var c=b[1]||"",a=b[8]||"";if(c+a===""||c==="{"&&a==="}"||c.toLowerCase()==="urn:uuid:"&&a==="")return(new d)._init(parseInt(b[2],
16),parseInt(b[3],16),parseInt(b[4],16),parseInt(b[5],16),parseInt(b[6],16),parseInt(b[7],16))}return null};d.prototype._init=function(){var b=d.FIELD_NAMES,c=d.FIELD_SIZES,a=d._binAligner,e=d._hexAligner;this.intFields=Array(6);this.bitFields=Array(6);this.hexFields=Array(6);for(var g=0;g<6;g++){var k=parseInt(arguments[g]||0);this.intFields[g]=this.intFields[b[g]]=k;this.bitFields[g]=this.bitFields[b[g]]=a(k,c[g]);this.hexFields[g]=this.hexFields[b[g]]=e(k,c[g]/4)}this.version=this.intFields.timeHiAndVersion>>
12&15;this.bitString=this.bitFields.join("");this.hexString=this.hexFields[0]+"-"+this.hexFields[1]+"-"+this.hexFields[2]+"-"+this.hexFields[3]+this.hexFields[4]+"-"+this.hexFields[5];this.urn="urn:uuid:"+this.hexString;return this};d._binAligner=d._getIntAligner(2);d.prototype.toString=function(){return this.hexString};d.prototype.equals=function(b){if(!(b instanceof d))return false;for(var c=0;c<6;c++)if(this.intFields[c]!==b.intFields[c])return false;return true};d.genV1=function(){var b=(new Date).getTime(),
c=d._state;b!=c.timestamp?(b<c.timestamp&&c.sequence++,c.timestamp=b,c.tick=d._getRandomInt(4)):Math.random()<d._tsRatio&&c.tick<9984?c.tick+=1+d._getRandomInt(4):c.sequence++;var b=d._getTimeFieldValues(c.timestamp),a=b.low+c.tick,e=b.hi&4095|4096;c.sequence&=16383;var g=c.sequence>>>8|128,k=c.sequence&255;return(new d)._init(a,b.mid,e,g,k,c.node)};d.resetState=function(){d._state=new d._state.constructor};d._tsRatio=0.25;d._state=new function(){var b=d._getRandomInt;this.timestamp=0;this.sequence=
b(14);this.node=(b(8)|1)*1099511627776+b(40);this.tick=b(4)};d._getTimeFieldValues=function(b){b-=Date.UTC(1582,9,15);var c=b/4294967296*1E4&268435455;return{low:(b&268435455)*1E4%4294967296,mid:c&65535,hi:c>>>16,timestamp:b}};d.makeBackwardCompatible=function(){var b=d.generate;d.generate=function(c){return c&&c.version==1?d.genV1().hexString:b.call(d)};d.makeBackwardCompatible=function(){}};d.overwrittenUUID=a;return d}(UUID);
var FlashDetect=new function(){var a=this;a.installed=false;a.raw="";a.major=-1;a.minor=-1;a.revision=-1;a.revisionStr="";var d=[{name:"ShockwaveFlash.ShockwaveFlash.7",version:function(c){return b(c)}},{name:"ShockwaveFlash.ShockwaveFlash.6",version:function(c){var a="6,0,21";try{c.AllowScriptAccess="always",a=b(c)}catch(d){}return a}},{name:"ShockwaveFlash.ShockwaveFlash",version:function(c){return b(c)}}],b=function(b){var a=-1;try{a=b.GetVariable("$version")}catch(d){}return a};a.majorAtLeast=
function(b){return a.major>=b};a.minorAtLeast=function(b){return a.minor>=b};a.revisionAtLeast=function(b){return a.revision>=b};a.versionAtLeast=function(b){var d=[a.major,a.minor,a.revision],e=Math.min(d.length,arguments.length);for(i=0;i<e;i++)if(d[i]>=arguments[i]){if(!(i+1<e&&d[i]==arguments[i]))return true}else return false};a.FlashDetect=function(){var b,f,e,g,k;if(navigator.plugins&&navigator.plugins.length>0){var h=navigator.mimeTypes;if(h&&h["application/x-shockwave-flash"]&&h["application/x-shockwave-flash"].enabledPlugin&&
h["application/x-shockwave-flash"].enabledPlugin.description){b=h=h["application/x-shockwave-flash"].enabledPlugin.description;var h=b.split(/ +/),j=h[2].split(/\./),h=h[3];f=parseInt(j[0],10);e=parseInt(j[1],10);g=h;k=parseInt(h.replace(/[a-zA-Z]/g,""),10)||a.revision;a.raw=b;a.major=f;a.minor=e;a.revisionStr=g;a.revision=k;a.installed=true}}else if(navigator.appVersion.indexOf("Mac")==-1&&window.execScript){h=-1;for(j=0;j<d.length&&h==-1;j++){b=-1;try{b=new ActiveXObject(d[j].name)}catch(m){b={activeXError:true}}if(!b.activeXError&&
(a.installed=true,h=d[j].version(b),h!=-1))b=h,g=b.split(","),f=parseInt(g[0].split(" ")[1],10),e=parseInt(g[1],10),k=parseInt(g[2],10),g=g[2],a.raw=b,a.major=f,a.minor=e,a.revision=k,a.revisionStr=g}}}()};FlashDetect.JS_RELEASE="1.0.4";var GV=GV||{};GV.Ajax={};GV.Data={};GV.External={};GV.Tasks={};GV.Utils={};
GV.applicationConfig={flashPlayerUrl:"http://player.goviral-content.com/player.php",flashPlayerSkinPath:"http://player.goviral-content.com/assets/latest/",flashPlayerPluginPath:"http://player.goviral-content.com/modules/",flashPlayerPlaylistPath:"http://s.srvntrk.com/handler/staticPlaylist",previewFlashPlayerPingUrl:"http://sp-work.goviral-content.com/handler/preview-tracking",flashPlayerVersion:"2.3.5",minFlashVersion:"9",htmlPlayerVersion:"1",youtubePlayerVersion:"1",elementAttributeName:"data-gv-player",
serviceRequestTimeout:"10000",serveandtrackPlaylistUrl:"http://s.srvntrk.com/handler/dynamicPlaylist?cw=1447928&videoID={{videoId}}&format={{requestType}}&fallback=1",serveandtrackPlaylistCallbackName:"callback",serveandtrackPingUrl:"http://s.srvntrk.com/handler/img?v={{v}}&videoID={{videoID}}&cw=1447928&a={{a}}&type={{type}}&pID={{pID}}&psid={{psid}}&version={{version}}&playertype={{playertype}}&dm={{deliveryMethod}}&dmv={{deliveryMethodVersion}}&inid={{inid}}&ppx={{playerPositionX}}&ppy={{playerPositionY}}&wsw={{windowSizeWidth}}&wsh={{windowSizeHeight}}&psw={{playerSizeWidth}}&psh={{playerSizeHeight}}&r={{r}}&s={{s}}&ts={{ts}}",
blacklistServiceUrl:"http://player-services.goviral-content.com/blacklist/index/check?placementId={{placementId}}&placementUrl={{placementUrl}}&format={{requestType}}",blacklistServiceCallbackName:"blacklistCallback",customTemplateServiceUrl:"http://player-services.goviral-content.com/template/index/find?contentId={{videoId}}&format={{requestType}}",customTemplateServiceCallbackName:"templateCallback",fallbackServiceUrl:"http://player-services.goviral-content.com/fallback/index/find?placementVersionId={{placementVersionId}}&format={{requestType}}",
fallbackServiceCallbackName:"fallbackCallback",diagnosticsServiceUrl:"http://player-diagnostics.goviral.com/handler.php?sourceId=2&placementType={{placementType}}&placementUrl={{placementUrl}}&playlistLoadingTime=&ts={{ts}}&cw=1447928&pID={{pID}}&aspect=&error={{error}}&errorMsg={{errorMsg}}&videoID={{videoID}}&height=&width=&memory=&version={{version}}&userAgent={{userAgent}}",comscoreTrackerUrl:"http://b.scorecardresearch.com/p?c1=3&c2=16580731&c3=%%BE_CAMPAIGN_ID%%&c4=%%BE_VIDEO_ID%%&c5=%%BE_CW%%&c6=&c10=1&c11=&c13=%%BE_PLAYER_SIZE%%&c16=BeOn&cj=1&ax_fwd=1&rn=%%TIMESTAMP%%",
adcomSIPUrl:"http://ace-tag.advertising.com/action/type=160956971/bins=1/rich=0/mnum=1516/site=703223/ejob=0/xssale=PRICE/xsordnm=ORDERID/xsstr1=%%BE_INID%%/betr=A71901=[+]TY1[168],TY2[720],TY3[8760]",researchNowTrackerUrl:"http://tag.researchnow.com/t/beacon?pr=621&ca=%%BE_CAMPAIGN_ID%%&pl=%%BE_CW%%&cr=%%BE_VIDEO_ID%%&si=&adn=3&tt=3&ord=%%TIMESTAMP%%"};
if("https:"==document.location.protocol)for(var p in GV.applicationConfig)if(GV.applicationConfig.hasOwnProperty(p)&&/^http\:/.test(GV.applicationConfig[p])&&(GV.applicationConfig[p]=GV.applicationConfig[p].replace(/^http\:/,"https:"),p.inArray(["flashPlayerUrl","flashPlayerSkinPath","flashPlayerPluginPath"]))){window.console&&console.log("will change domain for:",p);var url=GV.applicationConfig[p],tld=document.location.host.replace(/^.*?\./,""),url=url.replace(/goviral\-content\.com/,tld);GV.applicationConfig[p]=
url}GV.Utils.Functions={curry:function(a){var d=Array.prototype.slice.call(arguments,1);return function(){return a.apply(this,d.concat(Array.prototype.slice.call(arguments)))}},mergeObjects:function(a,d){for(var b in d)a[b]=d[b];return a}};
GV.Utils.Event=function(){var a=[],d=function(b,a){var d=a?a:window.event;if(d.srcElement)d.target=d.srcElement;b.call(this,d)},b=function(b,a,d){b.removeEventListener?b.removeEventListener(a,d,false):b.detachEvent&&b.detachEvent("on"+a,d)};return{create:function(b,f,e){e=GV.Utils.Functions.curry(d,e);b.addEventListener?b.addEventListener(f,e,false):b.attachEvent&&b.attachEvent("on"+f,e);a.push({element:b,type:f,handler:e});return e},remove:b,removeAll:function(d,f){for(var e=a.length-1;e>=0;e--){var g=
a[e];g.element===d&&g.type===f&&(b(d,f,g.handler),a.splice(e,1))}}}}();
GV.Utils.Dom=function(){var a=function(a){function b(f,e){typeof f==="undefined"&&(f=true);for(typeof e==="undefined"&&(e=0);f;){var g=a[e];if(g){if(!g.type||g.type==="text/javascript"){var k=0,h=true,j=document.createElement("script");j.type="text/javascript";if(g.innerText||g.innerHTML||g.text)try{j.appendChild(document.createTextNode(g.text))}catch(m){j.text=g.text}else if(g.src)j.src=g.src,h=f=false,j.onload=j.onreadystatechange=function(){if(this.readyState&&this.readyState!=="complete"&&this.readyState!==
"loaded"||k)return false;this.onload=this.onreadystatechange=null;c.removeChild(this);f=true;k=1;b(f,e)};c.insertBefore(j,c.firstChild);h&&c.removeChild(j)}e++}else f=false}}var c=document.getElementsByTagName("head")[0]||document.documentElement;b()};return{createElement:function(a,b){if(typeof a!=="string"||!a)return null;var c=document.createElement(a);if(b)c.className=b;c.css=function(b){for(var a in b)try{var d=b[a];a==="float"&&(a=c.style.cssFloat?"styleFloat":"cssFloat");typeof d==="number"&&
(d+="px");c.style[a]=d}catch(k){}};return c},addClass:function(a,b){var c,f,e,g;if(b&&typeof b==="string"&&(c=b.split(/\s+/),a.nodeType===1))if(!a.className&&c.length===1)a.className=b;else{f=" "+a.className+" ";for(e=0,g=c.length;e<g;e++)~f.indexOf(" "+c[e]+" ")||(f+=c[e]+" ");a.className=f}},removeClass:function(a,b){var c,f,e,g;if(b&&typeof b==="string"||b===void 0)if(c=(b||"").split(/\s+/),a.nodeType===1&&a.className)if(b){f=(" "+a.className+" ").replace(/[\n\t\r]/g," ");for(e=0,g=c.length;e<
g;e++)f=f.replace(" "+c[e]+" "," ");a.className=f}else a.className=""},width:function(a){if(!a)return null;if(a&&typeof a==="object"&&"setInterval"in a){var b=a.document.documentElement.clientWidth;return a.document.compatMode==="CSS1Compat"&&b||a.document.body.clientWidth||b}else return a.nodeType===9?Math.max(a.documentElement.clientWidth,a.body.scrollWidth,a.documentElement.scrollWidth,a.body.offsetWidth,a.documentElement.offsetWidth):a.offsetWidth},getStyledWidth:function(a){if(!a)return null;
return typeof a.style!=="undefined"&&typeof a.style.width!=="undefined"&&(a=parseInt(a.style.width,10),!isNaN(a))?a:0},height:function(a){if(!a)return null;if(a&&typeof a==="object"&&"setInterval"in a){var b=a.document.documentElement.clientHeight;return a.document.compatMode==="CSS1Compat"&&b||a.document.body.clientHeight||b}else return a.nodeType===9?Math.max(a.documentElement.clientHeight,a.body.scrollHeight,a.documentElement.scrollHeight,a.body.offsetHeight,a.documentElement.offsetHeight):a.offsetHeight},
getStyledHeight:function(a){if(!a)return null;return typeof a.style!=="undefined"&&typeof a.style.height!=="undefined"&&(a=parseInt(a.style.height,10),!isNaN(a))?a:0},position:function(a){return!a?null:a.getBoundingClientRect?a.getBoundingClientRect():null},insertElementImmediately:function(a){if(a&&typeof a.innerHTML!=="undefined"){var b=document.createElement("div");b.appendChild(a);document.write(b.innerHTML)}},insertHtmlWithScripts:function(d,b){var b=["<div>&nbsp;</div>",b].join(""),c=document.createDocumentFragment(),
f=document.createElement("div");c.appendChild(f);f.innerHTML=b;f.hasChildNodes()&&f.removeChild(f.firstChild);d.appendChild(c.firstChild);c=d.getElementsByTagName("script");a(c)}}}();try{var clog=Function.prototype.bind.call(console.log,console)}catch(e$$20){}GV.Utils.Logger={log:function(){try{"undefined"!==typeof Cookies.get("gvlog")&&window.console&&clog.apply(console,arguments)}catch(a){}}};if(!window.gvlog)window.gvlog=GV.Utils.Logger.log;
GV.Utils.QueryString=function(){return{appendParameters:function(a,d){if(typeof a!=="string"&&!a)throw Error("No URL supplied");else if(d){var b=a.indexOf("?")===-1,c=[a],f;for(f in d)d.hasOwnProperty(f)&&(c.push([b?"?":"&",encodeURIComponent(f),"=",encodeURIComponent(d[f])].join("")),b&&(b=false));return c.join("")}else return a},getParameters:function(a){if(a){var d={};if(a.indexOf("?")>-1&&(a=a.split("?")[1].split("&"))&&a.length)for(var b=0;b<a.length;b++){var c=a[b].split("="),f=decodeURIComponent(c[0]),
c=decodeURIComponent(c[1]);d[f]=c}return d}else throw Error("You must provide a URL to get query string parameters from");}}}();
GV.Instance=function(a,d){Date.prototype.toISOString||function(){function a(b){b=String(b);b.length===1&&(b="0"+b);return b}Date.prototype.toISOString=function(){return this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"."+String((this.getUTCMilliseconds()/1E3).toFixed(3)).slice(2,5)+"Z"}}();this._padString=navigator.userAgent+(new Date).toISOString().replace(/\.\d{3}(Z)$/,"$1");this._salt=d?
this._padString+d:this._padString;this._id=void 0;this._mode=a;this._defaultMode="uuid"};GV.Instance.prototype.setSalt=function(a){this._salt=a};GV.Instance.prototype.getID=function(){this.setMode(this._mode);this._id||this.generateID(this._mode);return this._mode=="uuid"?this._id.toString().toUpperCase():this._id};GV.Instance.prototype.toHex=function(a){for(var d="",b=0;b<a.length;b++)d+=""+a.charCodeAt(b).toString(16);return d};
GV.Instance.prototype.toHash=function(a){var d=0,b,c;if(a.length===0)return d;for(b=0;b<a.length;b++)c=a.charCodeAt(b),d=(d<<5)-d+c,d&=d;return d};GV.Instance.prototype.generateID=function(a){switch(a){case "uuid":this._generateUUID();break;case "md5":this._generateMD5();break;case "sha1":this._generateSHA1();break;default:this._generateUUID()}};GV.Instance.prototype.setMode=function(a){for(var d=["uuid","md5","sha1"],b=false,c=d.length-1;c>=0;c--)d[c]==a&&(b=true);this._mode=b?a:this._defaultMode};
GV.Instance.prototype._generateUUID=function(){this._id=UUID.genV4()};GV.Instance.prototype._generateMD5=function(){this._id=hex_md5(this._salt)};GV.Instance.prototype._generateSHA1=function(){this._id=hex_sha1(this._salt)};
GV.Embedder=function(){var a=["cw","psid","r","s"],d=function(a){var b=document.createElement("div");b.setAttribute("id",a);return b},b=function(a){a.poR=document.referrer;a.poS=document.location.href},c=function(a,b,c){a.setAttribute("width",b);a.setAttribute("height",c)},f=function(a){a.setAttribute("frameBorder","0");a.setAttribute("scrolling","no");a.style.border="0px";a.style.margin="0px";a.style.padding="0px"},e=function(b,c){var d=document.getElementById(b);if(d){var d=GV.Utils.QueryString.getParameters(d.getAttribute("src")),
e;for(e in d)if(d.hasOwnProperty(e))for(var f=0;f<a.length;f++)if(e===a[f]){c[e]=d[e];break}}},g=function(a){a.target.style.visibility="visible"};return{embedIframe:function(a){if(a&&a.target&&a.url){var h=document.getElementById(a.target);h||(GV.Utils.Dom.insertElementImmediately(d(a.target)),h=document.getElementById(a.target));if(h){var j=document.createElement("iframe");j.setAttribute("id","gv-iframe");c(j,a.w,a.h);f(j);var m=a.frame||{};b(m);var n=h,o=curtop=0;if(n.offsetParent){do o+=n.offsetLeft,
curtop+=n.offsetTop;while(n=n.offsetParent)}m.playerPositionX=o;m.playerPositionY=curtop;a.script&&e(a.script,m);var q=GV.Utils.QueryString.appendParameters(a.url,m);j.setAttribute("src",q);j.style.visibility="hidden";GV.Utils.Event.create(j,"load",g);h.appendChild(j);var l=0,r=setInterval(function(){var a=j.getBoundingClientRect();a.top>=0&&a.left>=0&&a.bottom<=window.innerHeight&&a.right<=window.innerWidth?l+=3:l=0;l>=6&&(j.setAttribute("src",q+"#"),clearInterval(r))},3E3)}}},iframeId:"gv-iframe"}}();
(function(){inid=(new GV.Instance("uuid")).getID();window.initping=1;var a;a="tracking_srv".replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");a=RegExp("[\\?&]"+a+"=([^&#]*)").exec(location.search);a=a==null?"":decodeURIComponent(a[1].replace(/\+/g," "));var d=/test\.publisher\.com/.test(document.location.href)?"test.publisher.com/ping.php?v=1":"s.srvntrk.com/handler/img?v=1";sapMode="";pingUrl="//"+d+"&videoID=0&cw=1447928&type=201&psid="+("undefined"!==typeof psid?psid:"")+"&version=2.3.5&playertype="+
(FlashDetect.installed?1:2)+"&inid="+inid+"&r="+encodeURIComponent(document.referrer.substring(0,500))+"&s="+encodeURIComponent(document.location.href.substring(0,500))+"&ts="+(new Date).getTime();a&&(pingUrl=pingUrl.replace(/^[a-z]*:\/\/[^\?]*/,a));try{(new Image).src=pingUrl}catch(b){window.console&&console.log("ERROR SENDING INIT_PING: ",b.message)}})();
GV.Embedder.embedIframe({frame:{ahide:"false",bgCol:"ffffff",cw:"undefined"!=typeof playerEnv&&playerEnv=="5x5m"?0:"1447928",videoId:"0",sapMode:"",fall:"html",pvid:"4336458813553375091447928",txtCol:"000000",skin:"light",wmode:"window",deliveryMethod:"1",deliveryMethodVersionSP:"1.0.0",deliveryMethodVersionSAP:"2.0.0",psid:"undefined"!=typeof psid?psid:0,adcomPlay:"undefined"!=
typeof customTrackPlay?/\%3A\%2F/.test(customTrackPlay)?customTrackPlay:encodeURIComponent(customTrackPlay):"undefined"!=typeof adcomPlay?adcomPlay:"",adcom20:"undefined"!=typeof customTrack20?/\%3A\%2F/.test(customTrack20)?customTrack20:encodeURIComponent(customTrack20):"undefined"!=typeof adcom20?adcom20:"",adcom40:"undefined"!=typeof customTrack40?/\%3A\%2F/.test(customTrack40)?customTrack40:encodeURIComponent(customTrack40):"undefined"!=typeof adcom40?adcom40:"",adcom60:"undefined"!=typeof customTrack60?
/\%3A\%2F/.test(customTrack60)?customTrack60:encodeURIComponent(customTrack60):"undefined"!=typeof adcom60?adcom60:"",adcom80:"undefined"!=typeof customTrack80?/\%3A\%2F/.test(customTrack80)?customTrack80:encodeURIComponent(customTrack80):"undefined"!=typeof adcom80?adcom80:"",adcom100:"undefined"!=typeof customTrack100?/\%3A\%2F/.test(customTrack100)?customTrack100:encodeURIComponent(customTrack100):"undefined"!=typeof adcom100?adcom100:"",adcomRedirect:"undefined"!=typeof customTrackRedirect?/\%3A\%2F/.test(customTrackRedirect)?
customTrackRedirect:encodeURIComponent(customTrackRedirect):"undefined"!=typeof adcomRedirect?adcomRedirect:"",initping:"undefined"!==typeof initping?1:"",inid:"undefined"!==typeof inid?inid:"",playerSizeWidth:"400",playerSizeHeight:"267",windowSizeWidth:window.innerWidth,windowSizeHeight:window.innerHeight,forceCTPonVPAID:"undefined"!=typeof forceCTPonVPAID?forceCTPonVPAID:"",CTPCountdownSkip:"undefined"!=typeof CTPCountdownSkip?CTPCountdownSkip:"",CTPCountdownTime:"undefined"!=
typeof CTPCountdownTime?CTPCountdownTime:"",CTPPlaybackSkip:"undefined"!=typeof CTPPlaybackSkip?CTPPlaybackSkip:"",disableTooltip:"undefined"!=typeof disableTooltip?disableTooltip:""},h:"267",script:"gv_script_4336458813553375091447928",target:"gv_target_4336458813553375091447928",url:"https:"==document.location.protocol?"http://sp-work.goviral-content.com/templates/custom.html".replace(/^http\:/,"https:"):"http://sp-work.goviral-content.com/templates/custom.html",w:"400"});
