include ../../Makefile.inc

P=memalloc/part5/

all:	
	${GCC} mincore.c -o mincore ${ECHO}mincore.c
	${GCC} mlockall.c -o mlockall ${ECHO}mlockall.c
	${GCC} mlock.c -o mlock ${ECHO}mlock.c
clean : 
	${RM} *~  mincore mlockall mlock

