var linkText = 'Provide feedback'; // Another instance inside openWindow()

document.writeln("<br />[ <a href=\"#\" onclick=\"openWindow();return false\">" + linkText + "</a> ]<br /><br />");

function openWindow() {
	var pageURL = window.document.URL;
	var pageTitle = window.document.title;
	var email = 'compinfo@ca.ibm.com';
	var windowTitle = 'Provide feedback on this documentation';
	var popupWidth = 600;
	var popupHeight = 260;
	
	// Truncate the URL to remove server details
	// Just keep the plugin name and filepath
	var URLindex = pageURL.indexOf('/topic/') + 7;
	pageURL = pageURL.substring(URLindex);
	
	// Remove HTML anchor (if it exists)
	var anchorIndex = pageURL.indexOf('#');
	if(anchorIndex != -1) {
		// Anchor exists, remove it
		pageURL = pageURL.substring(0,anchorIndex);
	}
	
	// Remove extra characters generated by search engine
	var resultofIndex = pageURL.indexOf('?resultof');
	if(resultofIndex != -1) {
		// extra characters exist, remove them
		pageURL = pageURL.substring(0,resultofIndex);
	}
		
	// Determine variables for centering the window
	var posLeft = (screen.width/2) - (popupWidth/2);
	var posTop = (screen.height/2) - (popupHeight/2);
	
	var n = new Date();
	var x = window.open('','feedback_window'+n.getTime(),'width=' + popupWidth + ',height=' + popupHeight + ',left=' + posLeft + ',top=' + posTop + ',menubars,resizable');
	x.document.writeln('<html>');
	x.document.writeln('<head>');
	x.document.writeln('<title>' + windowTitle + '</title>');
	x.document.writeln('<style type="text/css">');
	x.document.writeln('body {');
	x.document.writeln(' background-color: #ffffff;');
	x.document.writeln(' color: Black;');
	x.document.writeln(' font-family: "arial";');
	x.document.writeln(' font-size: .8em;');
	x.document.writeln(' padding: 20px;');
	x.document.writeln(' padding-top: 30px;');
	x.document.writeln('}');
	x.document.writeln('</style>');
	x.document.writeln('<script type="text/javascript">
<!--
if (parent.ContentToolbarFrame && parent.ContentToolbarFrame.setButtonState) parent.ContentToolbarFrame.setButtonState("toggle_highlight","hidden");
-->
</script>

</head>');
	x.document.writeln('<body>');
	x.document.writeln('There are two ways to provide feedback about this page:');
	x.document.writeln('<ul>');
	x.document.writeln('  <li>Click this <a href="mailto:' + email + '?subject=Feedback on \'' + pageTitle + '\' @ [' + pageURL + ']">link</a> to compose a message using your default mail client.<br />Details about the page you were viewing are automatically included.<br /><br /></li>');
	x.document.writeln('  <li>Send an e-mail to <strong>compinfo@ca.ibm.com</strong>, and include the following information<br />in the subject line:<br />');
	x.document.writeln('<div style="padding: 6px; background-color: #DEDEEE; font-size: 1.0em">Feedback on \'' + pageTitle + '\' @ [' + pageURL + ']</div></li>');
	x.document.writeln('</ul>');
	x.document.writeln('</body>');
	x.document.writeln('</html>');
}