include ../../Makefile.inc

P=io/part1/

all:	
	${GCC} perror.c -o perror ${ECHO}perror.c
	${GCC} read.c -o read 	${ECHO}read.c
	${GCC} read_ahead.c -o read_ahead ${ECHO}read_ahead.c
	${GCC} readv.c -o readv ${ECHO}readv.c
	${GCC} write1.c -o write1 ${ECHO}write1.c
	${GCC} create.c -o create ${ECHO}create.c
	${GCC} directio.c -o directio ${ECHO}directio.c
	${GCC} lseek.c -o lseek ${ECHO}lseek.c
	${GCC} open.c -o open ${ECHO}open.c
	${GCC} read1.c -o read1 ${ECHO}read1.c
	${GCC} sync.c -o sync ${ECHO}sync.c
	${GCC} write.c -o write ${ECHO}write.c
	${GCC} writev.c -o writev ${ECHO}writev.c
	${GCC} copysync.c -o copysync ${ECHO}copysync.c
	${GCC} direct_read.c -o direct_read ${ECHO}direct_read.c
	${GCC} fstatcopy.c -o fstatcopy ${ECHO}fstatcopy.c
	${GCC} app.c -o app ${ECHO}app.c
	${GCC} test.c -o test ${ECHO}test.c
	${GCC} copy.c -o copy ${ECHO}copy.c
	${GCC} fstat.c -o fstat ${ECHO}fstat.c
	${GCC} fs_stats.c -o fs_stats ${ECHO}fs_stats.c
clean : 
	${RM} perror read read_ahead readv write1 copysync direct_read create directio lseek open read1 sync write writev copy.mp4 copysyncdirect_read fstatcopy app test copy fs_stats fstat
